import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

# font
[font]
size = 16
normal = { family = "Courier New", style = "Regular" }

[window]
opacity = 0.7
blur = true
decorations = "Transparent"
padding = {x = 10, y = 30}
dynamic_padding = true
dimensions = {columns = 167, lines = 52}
position = {x = 70, y = 105}
# startup_mode= "SimpleFullscreen"

[cursor]
style = {shape = "Beam", blinking = "On"}
